name: Tests and Allure

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Pytest with Allure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest pytest-playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run Pytest with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report (HTML)
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
